apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-service
  description: Backstage control repo
  annotations:
    github.com/project-slug: 'lukasb27/backstage-app'
spec:
  type: service
  lifecycle: production
  owner: lukas
