apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-service
  description: Backstage control repo
  annotations:
    github.com/project-slug: 'lukasb27/backstage-app'
spec:
  type: website
  lifecycle: production
  owner: lukas
  system: backstage

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: language-tutor
  description: Langugage tutor repo
  annotations:
    github.com/project-slug: 'lukasb27/language-tutor'
spec:
  type: service
  lifecycle: experimental
  owner: lukas
  system: language-tutor

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fermentation-station-agent
  description: Fermentation station agent code
  annotations:
    github.com/project-slug: 'lukasb27/fermentation-station-agent'
spec:
  type: service
  lifecycle: experimental
  owner: lukas
  system: fermentation-station

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fermentation-station-argocd-control
  description: Fermentation station argo cd control repo 
  annotations:
    github.com/project-slug: 'lukasb27/fermentation-station-argocd-control'
spec:
  type: service
  lifecycle: experimental
  owner: lukas
  system: fermentation-station