site_name: 'backstage-service'
site_description: 'Backstage control repo'
nav:
  - Home: index.md
  - Guides:
      - Building the Stale Environment Finder Plugin: stale-environment-finder-plugin-guide.md
  - ADRs:
      - Custom Image + GitOps CD: custom-backstage-image-gitops-cd-adr.md
      - DB Migration PreSync Hook (Rejected): backstage-db-migration-presync-hook-adr.md
      - RollingUpdate preStop Hook: backstage-prestop-hook-adr.md
plugins:
  - techdocs-core
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
